#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo 'please be patient, this may take a while...'

# Check ESLint Standards
# npm run lint ||
npm run warnlint ||
(
    echo '🔨❌ you have a problem in your code. Check linter 🔨❌
          Run npm run lint, add changes and try commit again.';
    false;
)

npm run prettify ||
(
    echo 'failed formatting code with prettier...!';
    false;
)

echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'